name: g-splat
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - cuda-toolkit
  - plyfile
  - python=3.12
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pyglm
  - matplotlib
  - pip:
    - opencv-python
    - joblib
